### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by ToniCreswell** [greentfrapp/adversarialautoencoder#1]
`$python adversarialautoencoder.py --samplegrid -rz1 [-2,2] -rz2 [-2,2]`

Gives the following error: 
Traceback (most recent call last):
  File "adversarialautoencoder.py", line 566, in <module>
    main()
  File "adversarialautoencoder.py", line 551, in main
    y_range=args.range_z2)
  File "adversarialautoencoder.py", line 280, in generate_sample_image_grid
    x_points = np.arange(x_range[0], x_range[1], step_x).astype(np.float32)
ZeroDivisionError: division by zero

Using `np.linspace(x_range[0], x_range[1], step_x)` may be better.

**Comment by greentfrapp** [comment]
Thanks for the suggestion, actually didn't know about `np.linspace`! Adopted it and removed the earlier cumbersome chunk of code (side note, I think you meant `np.linspace(x_range[0], x_range[1], n_x)`)

Also, I made some changes to the way the folders are named, replacing `:` with `-` because of some Windows issue, just fyi.

Thanks for checking out the repo!
